### ISSUE TITLE
Update transitive dependencies to fix vulnerability 

### ISSUE THREAD

**Issue by lukewhitehouse** [percy/percy-playwright#446]
## The problem

There is a high severity alert out for versions of `path-to-regexp`: https://github.com/advisories/GHSA-9wv6-86v2-598j

## Details

This package is a transitive dependency for a couple of direct dependencies to `@percy/playwright`, which will need updating. These include:
- updating `@percy/cli`, fixed in `v1.29.4` https://github.com/percy/cli/releases/tag/v1.29.4
- updating `sinon`, fixed in `v18.0.1` https://github.com/sinonjs/sinon/blob/main/CHANGES.md#1801

This repo has 2 bumps to get us started:
- https://github.com/percy/percy-playwright/pull/445  – seems good to go
- https://github.com/percy/percy-playwright/pull/444 – breaking changes from v18 -> v19 that may fail tests. Might be easier to upgrade the patch version instead for now.

Is this something that could be looked at? Happy to help with the Sinon bump

**Comment by lukewhitehouse** [comment]
On reviewing https://github.com/percy/percy-playwright/pull/444 CI steps it looks the node version needs updating too.

**Comment by lukewhitehouse** [comment]
I've created a PR for the sinon and node upgrades which combined with https://github.com/percy/percy-playwright/pull/445, should fix the vulnerability found in older versions of `path-to-regexp`. Would love to hear your thoughts here @prklm10 & @shantanuk-browserstack

**Comment by prklm10** [comment]
@lukewhitehouse thanks for raising the pr for this. We will be trying to update the sinon patch version instead of upgrading node.

**Comment by prklm10** [comment]
Hi @lukewhitehouse we have released v1.0.7 that has the security patch for path-to-regex.

**Comment by prklm10** [comment]
We are closing this issue.

**Comment by lukewhitehouse** [comment]
Hi @prklm10, I've been away the last couple of weeks due to a family emergency but I'm pleased to see this was resolved whilst I was away. Apologies for the delay in getting back to you but I really do appreciate the effort you and the team have put into this.
